import "./globals.css";
import { Work_Sans } from "next/font/google";
import LocalFont from "next/font/local";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-work-sans",
});
export const metadata = {
  title: "NFT MarketPlace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} bg-[#2B2B2B] min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
